# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Person.create(:name => "Myriel" , :group => 1, :index => 0)
Person.create(:name => "Napoleon" , :group => 1, :index => 1)
Person.create(:name => "Mlle.Baptistine" , :group => 1, :index => 2)
Person.create(:name => "Mme.Magloire" , :group => 1, :index => 3)
Person.create(:name => "CountessdeLo" , :group => 1, :index => 4 )
Person.create(:name => "Geborand" , :group => 1, :index => 5 )
Person.create(:name => "Champtercier" , :group => 1, :index => 6 )
Person.create(:name => "Cravatte" , :group => 1, :index => 7 )
Person.create(:name => "Count" , :group => 1, :index => 8 )
Person.create(:name => "OldMan" , :group => 1, :index => 9 )
Person.create(:name => "Labarre" , :group => 2, :index => 10 )
Person.create(:name => "Valjean" , :group => 2, :index => 11 )
Person.create(:name => "Marguerite" , :group => 3, :index => 12 )
Person.create(:name => "Mme.deR" , :group => 2, :index => 13 )
Person.create(:name => "Isabeau" , :group => 2, :index => 14 )
Person.create(:name => "Gervais" , :group => 2, :index => 15 )
Person.create(:name => "Tholomyes" , :group => 3, :index => 16 )
Person.create(:name => "Listolier" , :group => 3, :index => 17 )
Person.create(:name => "Fameuil" , :group => 3, :index => 18 )
Person.create(:name => "Blacheville" , :group => 3, :index => 19 )
Person.create(:name => "Favourite" , :group => 3 , :index => 20)
Person.create(:name => "Dahlia" , :group => 3, :index => 21 )
Person.create(:name => "Zephine" , :group => 3, :index => 22 )
Person.create(:name => "Fantine" , :group => 3, :index => 23 )
Person.create(:name => "Mme.Thenardier" , :group => 4, :index => 24 )
Person.create(:name => "Thenardier" , :group => 4, :index => 25 )
Person.create(:name => "Cosette" , :group => 5, :index => 26 )
Person.create(:name => "Javert" , :group => 4, :index => 27 )
Person.create(:name => "Fauchelevent" , :group => 0, :index => 28 )
Person.create(:name => "Bamatabois" , :group => 2, :index => 29 )
Person.create(:name => "Perpetue" , :group => 3, :index => 30 )
Person.create(:name => "Simplice" , :group => 2, :index => 31 )
Person.create(:name => "Scaufflaire" , :group => 2, :index => 32 )
Person.create(:name => "Woman1" , :group => 2, :index => 33 )
Person.create(:name => "Judge" , :group => 2, :index => 34 )
Person.create(:name => "Champmathieu" , :group => 2, :index => 35 )
Person.create(:name => "Brevet" , :group => 2, :index => 36 )
Person.create(:name => "Chenildieu" , :group => 2, :index => 37 )
Person.create(:name => "Cochepaille" , :group => 2, :index => 38 )
Person.create(:name => "Pontmercy" , :group => 4 , :index => 39)
Person.create(:name => "Boulatruelle" , :group => 6, :index => 40 )
Person.create(:name => "Eponine" , :group => 4, :index => 41 )
Person.create(:name => "Anzelma" , :group => 4, :index => 42 )
Person.create(:name => "Woman2" , :group => 5, :index => 43 )
Person.create(:name => "MotherInnocent" , :group => 0, :index => 44 )
Person.create(:name => "Gribier" , :group => 0, :index => 45 )
Person.create(:name => "Jondrette" , :group => 7, :index => 46 )
Person.create(:name => "Mme.Burgon" , :group => 7, :index => 47 )
Person.create(:name => "Gavroche" , :group => 8, :index => 48 )
Person.create(:name => "Gillenormand" , :group => 5, :index => 49 )
Person.create(:name => "Magnon" , :group => 5, :index => 50 )
Person.create(:name => "Mlle.Gillenormand" , :group => 5, :index => 51 )
Person.create(:name => "Mme.Pontmercy" , :group => 5, :index => 52 )
Person.create(:name => "Mlle.Vaubois" , :group => 5, :index => 53 )
Person.create(:name => "Lt.Gillenormand" , :group => 5, :index => 54 )
Person.create(:name => "Marius" , :group => 8, :index => 55 )
Person.create(:name => "BaronessT" , :group => 5, :index => 56 )
Person.create(:name => "Mabeuf" , :group => 8, :index => 57 )
Person.create(:name => "Enjolras" , :group => 8, :index => 58 )
Person.create(:name => "Combeferre" , :group => 8, :index => 59 )
Person.create(:name => "Prouvaire" , :group => 8, :index => 60 )
Person.create(:name => "Feuilly" , :group => 8, :index => 61 )
Person.create(:name => "Courfeyrac" , :group => 8, :index => 62 )
Person.create(:name => "Bahorel" , :group => 8, :index => 63 )
Person.create(:name => "Bossuet" , :group => 8, :index => 64 )
Person.create(:name => "Joly" , :group => 8, :index => 65 )
Person.create(:name => "Grantaire" , :group => 8, :index => 66 )
Person.create(:name => "MotherPlutarch" , :group => 9, :index => 67 )
Person.create(:name => "Gueulemer" , :group => 4, :index => 68 )
Person.create(:name => "Babet" , :group => 4, :index => 69 )
Person.create(:name => "Claquesous" , :group => 4, :index => 70 )
Person.create(:name => "Montparnasse" , :group => 4, :index => 71 )
Person.create(:name => "Toussaint" , :group => 5, :index => 72 )
Person.create(:name => "Child1" , :group => 10, :index => 73 )
Person.create(:name => "Child2" , :group => 10, :index => 74 )
Person.create(:name => "Brujon" , :group => 4, :index => 75 )
Person.create(:name => "Mme.Hucheloup" , :group => 8, :index => 76) 

Link.create(:source => 1, :target => 0, :value => 1)
Link.create(:source => 2, :target => 0, :value => 8)
Link.create(:source => 3, :target => 0, :value => 20)
Link.create(:source => 3, :target => 2, :value => 61)
Link.create(:source => 4, :target => 0, :value => 11)
Link.create(:source => 5, :target => 0, :value => 11)
Link.create(:source => 6, :target => 0, :value => 11)
Link.create(:source => 7, :target => 0, :value => 11)
Link.create(:source => 8, :target => 0, :value => 21)
Link.create(:source => 9, :target => 0, :value => 11)
Link.create(:source => 11, :target => 10, :value => 11)
Link.create(:source => 11, :target => 3, :value => 31)
Link.create(:source => 11, :target => 2, :value => 31)
Link.create(:source => 11, :target => 0, :value => 51)
Link.create(:source => 12, :target => 11, :value => 11)
Link.create(:source => 13, :target => 11, :value => 11)
Link.create(:source => 14, :target => 11, :value => 11)
Link.create(:source => 15, :target => 11, :value => 11)
Link.create(:source => 17, :target => 16, :value => 41)
Link.create(:source => 18, :target => 16, :value => 41)
Link.create(:source => 18, :target => 17, :value => 41)
Link.create(:source => 19, :target => 16, :value => 41)
Link.create(:source => 19, :target => 17, :value => 41)
Link.create(:source => 19, :target => 18, :value => 41)
Link.create(:source => 20, :target => 16, :value => 31)
Link.create(:source => 20, :target => 17, :value => 31)
Link.create(:source => 20, :target => 18, :value => 31)
Link.create(:source => 20, :target => 19, :value => 41)
Link.create(:source => 21, :target => 16, :value => 31)
Link.create(:source => 21, :target => 18, :value => 31)
Link.create(:source => 21, :target => 19, :value => 31)
Link.create(:source => 21, :target => 20, :value => 51)
Link.create(:source => 22, :target => 16, :value => 31)
Link.create(:source => 22, :target => 17, :value => 31)
Link.create(:source => 22, :target => 18, :value => 3)
Link.create(:source => 22, :target => 19, :value => 3)
Link.create(:source => 22, :target => 20, :value => 4)
Link.create(:source => 22, :target => 21, :value => 4)
Link.create(:source => 23, :target => 16, :value => 3)
Link.create(:source => 23, :target => 17, :value => 3)
Link.create(:source => 23, :target => 18, :value => 3)
Link.create(:source => 23, :target => 19, :value => 3)
Link.create(:source => 23, :target => 20, :value => 4)
Link.create(:source => 23, :target => 21, :value => 4)
Link.create(:source => 23, :target => 22, :value => 4)
Link.create(:source => 23, :target => 12, :value => 2)
Link.create(:source => 23, :target => 11, :value => 9)
Link.create(:source => 24, :target => 23, :value => 2)
Link.create(:source => 24, :target => 11, :value => 7)
Link.create(:source => 25, :target => 24, :value => 13)
Link.create(:source => 25, :target => 23, :value => 1)
Link.create(:source => 25, :target => 11, :value => 12)
Link.create(:source => 26, :target => 24, :value => 4)
Link.create(:source => 26, :target => 11, :value => 31)
Link.create(:source => 26, :target => 16, :value => 1)
Link.create(:source => 26, :target => 25, :value => 1)
Link.create(:source => 27, :target => 11, :value => 17)
Link.create(:source => 27, :target => 23, :value => 5)
Link.create(:source => 27, :target => 25, :value => 5)
Link.create(:source => 27, :target => 24, :value => 1)
Link.create(:source => 27, :target => 26, :value => 1)
Link.create(:source => 28, :target => 11, :value => 8)
Link.create(:source => 28, :target => 27, :value => 1)
Link.create(:source => 29, :target => 23, :value => 1)
Link.create(:source => 29, :target => 27, :value => 1)
Link.create(:source => 29, :target => 11, :value => 2)
Link.create(:source => 30, :target => 23, :value => 1)
Link.create(:source => 31, :target => 30, :value => 2)
Link.create(:source => 31, :target => 11, :value => 3)
Link.create(:source => 31, :target => 23, :value => 2)
Link.create(:source => 31, :target => 27, :value => 1)
Link.create(:source => 32, :target => 11, :value => 1)
Link.create(:source => 33, :target => 11, :value => 2)
Link.create(:source => 33, :target => 27, :value => 1)
Link.create(:source => 34, :target => 11, :value => 3)
Link.create(:source => 34, :target => 29, :value => 2)
Link.create(:source => 35, :target => 11, :value => 3)
Link.create(:source => 35, :target => 34, :value => 3)
Link.create(:source => 35, :target => 29, :value => 2)
Link.create(:source => 36, :target => 34, :value => 2)
Link.create(:source => 36, :target => 35, :value => 2)
Link.create(:source => 36, :target => 11, :value => 2)
Link.create(:source => 36, :target => 29, :value => 1)
Link.create(:source => 37, :target => 34, :value => 2)
Link.create(:source => 37, :target => 35, :value => 2)
Link.create(:source => 37, :target => 36, :value => 2)
Link.create(:source => 37, :target => 11, :value => 2)
Link.create(:source => 37, :target => 29, :value => 1)
Link.create(:source => 38, :target => 34, :value => 2)
Link.create(:source => 38, :target => 35, :value => 2)
Link.create(:source => 38, :target => 36, :value => 2)
Link.create(:source => 38, :target => 37, :value => 2)
Link.create(:source => 38, :target => 11, :value => 2)
Link.create(:source => 38, :target => 29, :value => 1)
Link.create(:source => 39, :target => 25, :value => 1)
Link.create(:source => 40, :target => 25, :value => 1)
Link.create(:source => 41, :target => 24, :value => 2)
Link.create(:source => 41, :target => 25, :value => 3)
Link.create(:source => 42, :target => 41, :value => 2)
Link.create(:source => 42, :target => 25, :value => 2)
Link.create(:source => 42, :target => 24, :value => 1)
Link.create(:source => 43, :target => 11, :value => 3)
Link.create(:source => 43, :target => 26, :value => 1)
Link.create(:source => 43, :target => 27, :value => 1)
Link.create(:source => 44, :target => 28, :value => 3)
Link.create(:source => 44, :target => 11, :value => 1)
Link.create(:source => 45, :target => 28, :value => 2)
Link.create(:source => 47, :target => 46, :value => 1)
Link.create(:source => 48, :target => 47, :value => 2)
Link.create(:source => 48, :target => 25, :value => 1)
Link.create(:source => 48, :target => 27, :value => 1)
Link.create(:source => 48, :target => 11, :value => 1)
Link.create(:source => 49, :target => 26, :value => 3)
Link.create(:source => 49, :target => 11, :value => 2)
Link.create(:source => 50, :target => 49, :value => 1)
Link.create(:source => 50, :target => 24, :value => 1)
Link.create(:source => 51, :target => 49, :value => 9)
Link.create(:source => 51, :target => 26, :value => 2)
Link.create(:source => 51, :target => 11, :value => 2)
Link.create(:source => 52, :target => 51, :value => 1)
Link.create(:source => 52, :target => 39, :value => 1)
Link.create(:source => 53, :target => 51, :value => 1)
Link.create(:source => 54, :target => 51, :value => 2)
Link.create(:source => 54, :target => 49, :value => 1)
Link.create(:source => 54, :target => 26, :value => 1)
Link.create(:source => 55, :target => 51, :value => 6)
Link.create(:source => 55, :target => 49, :value => 12)
Link.create(:source => 55, :target => 39, :value => 1)
Link.create(:source => 55, :target => 54, :value => 1)
Link.create(:source => 55, :target => 26, :value => 21)
Link.create(:source => 55, :target => 11, :value => 19)
Link.create(:source => 55, :target => 16, :value => 1)
Link.create(:source => 55, :target => 25, :value => 2)
Link.create(:source => 55, :target => 41, :value => 5)
Link.create(:source => 55, :target => 48, :value => 4)
Link.create(:source => 56, :target => 49, :value => 1)
Link.create(:source => 56, :target => 55, :value => 1)
Link.create(:source => 57, :target => 55, :value => 1)
Link.create(:source => 57, :target => 41, :value => 1)
Link.create(:source => 57, :target => 48, :value => 1)
Link.create(:source => 58, :target => 55, :value => 7)
Link.create(:source => 58, :target => 48, :value => 7)
Link.create(:source => 58, :target => 27, :value => 6)
Link.create(:source => 58, :target => 57, :value => 1)
Link.create(:source => 58, :target => 11, :value => 4)
Link.create(:source => 59, :target => 58, :value => 15)
Link.create(:source => 59, :target => 55, :value => 5)
Link.create(:source => 59, :target => 48, :value => 6)
Link.create(:source => 59, :target => 57, :value => 2)
Link.create(:source => 60, :target => 48, :value => 1)
Link.create(:source => 60, :target => 58, :value => 4)
Link.create(:source => 60, :target => 59, :value => 2)
Link.create(:source => 61, :target => 48, :value => 2)
Link.create(:source => 61, :target => 58, :value => 6)
Link.create(:source => 61, :target => 60, :value => 2)
Link.create(:source => 61, :target => 59, :value => 5)
Link.create(:source => 61, :target => 57, :value => 1)
Link.create(:source => 61, :target => 55, :value => 1)
Link.create(:source => 62, :target => 55, :value => 9)
Link.create(:source => 62, :target => 58, :value => 17)
Link.create(:source => 62, :target => 59, :value => 13)
Link.create(:source => 62, :target => 48, :value => 7)
Link.create(:source => 62, :target => 57, :value => 2)
Link.create(:source => 62, :target => 41, :value => 1)
Link.create(:source => 62, :target => 61, :value => 6)
Link.create(:source => 62, :target => 60, :value => 3)
Link.create(:source => 63, :target => 59, :value => 5)
Link.create(:source => 63, :target => 48, :value => 5)
Link.create(:source => 63, :target => 62, :value => 6)
Link.create(:source => 63, :target => 57, :value => 2)
Link.create(:source => 63, :target => 58, :value => 4)
Link.create(:source => 63, :target => 61, :value => 3)
Link.create(:source => 63, :target => 60, :value => 2)
Link.create(:source => 63, :target => 55, :value => 1)
Link.create(:source => 64, :target => 55, :value => 5)
Link.create(:source => 64, :target => 62, :value => 12)
Link.create(:source => 64, :target => 48, :value => 5)
Link.create(:source => 64, :target => 63, :value => 4)
Link.create(:source => 64, :target => 58, :value => 10)
Link.create(:source => 64, :target => 61, :value => 6)
Link.create(:source => 64, :target => 60, :value => 2)
Link.create(:source => 64, :target => 59, :value => 9)
Link.create(:source => 64, :target => 57, :value => 1)
Link.create(:source => 64, :target => 11, :value => 1)
Link.create(:source => 65, :target => 63, :value => 5)
Link.create(:source => 65, :target => 64, :value => 7)
Link.create(:source => 65, :target => 48, :value => 3)
Link.create(:source => 65, :target => 62, :value => 5)
Link.create(:source => 65, :target => 58, :value => 5)
Link.create(:source => 65, :target => 61, :value => 5)
Link.create(:source => 65, :target => 60, :value => 2)
Link.create(:source => 65, :target => 59, :value => 5)
Link.create(:source => 65, :target => 57, :value => 1)
Link.create(:source => 65, :target => 55, :value => 2)
Link.create(:source => 66, :target => 64, :value => 3)
Link.create(:source => 66, :target => 58, :value => 3)
Link.create(:source => 66, :target => 59, :value => 1)
Link.create(:source => 66, :target => 62, :value => 2)
Link.create(:source => 66, :target => 65, :value => 2)
Link.create(:source => 66, :target => 48, :value => 1)
Link.create(:source => 66, :target => 63, :value => 1)
Link.create(:source => 66, :target => 61, :value => 1)
Link.create(:source => 66, :target => 60, :value => 1)
Link.create(:source => 67, :target => 57, :value => 3)
Link.create(:source => 68, :target => 25, :value => 5)
Link.create(:source => 68, :target => 11, :value => 1)
Link.create(:source => 68, :target => 24, :value => 1)
Link.create(:source => 68, :target => 27, :value => 1)
Link.create(:source => 68, :target => 48, :value => 1)
Link.create(:source => 68, :target => 41, :value => 1)
Link.create(:source => 69, :target => 25, :value => 6)
Link.create(:source => 69, :target => 68, :value => 6)
Link.create(:source => 69, :target => 11, :value => 1)
Link.create(:source => 69, :target => 24, :value => 1)
Link.create(:source => 69, :target => 27, :value => 2)
Link.create(:source => 69, :target => 48, :value => 1)
Link.create(:source => 69, :target => 41, :value => 1)
Link.create(:source => 70, :target => 25, :value => 4)
Link.create(:source => 70, :target => 69, :value => 4)
Link.create(:source => 70, :target => 68, :value => 4)
Link.create(:source => 70, :target => 11, :value => 1)
Link.create(:source => 70, :target => 24, :value => 1)
Link.create(:source => 70, :target => 27, :value => 1)
Link.create(:source => 70, :target => 41, :value => 1)
Link.create(:source => 70, :target => 58, :value => 1)
Link.create(:source => 71, :target => 27, :value => 1)
Link.create(:source => 71, :target => 69, :value => 2)
Link.create(:source => 71, :target => 68, :value => 2)
Link.create(:source => 71, :target => 70, :value => 2)
Link.create(:source => 71, :target => 11, :value => 1)
Link.create(:source => 71, :target => 48, :value => 1)
Link.create(:source => 71, :target => 41, :value => 1)
Link.create(:source => 71, :target => 25, :value => 1)
Link.create(:source => 72, :target => 26, :value => 2)
Link.create(:source => 72, :target => 27, :value => 1)
Link.create(:source => 72, :target => 11, :value => 1)
Link.create(:source => 73, :target => 48, :value => 2)
Link.create(:source => 74, :target => 48, :value => 2)
Link.create(:source => 74, :target => 73, :value => 3)
Link.create(:source => 75, :target => 69, :value => 3)
Link.create(:source => 75, :target => 68, :value => 3)
Link.create(:source => 75, :target => 25, :value => 3)
Link.create(:source => 75, :target => 48, :value => 1)
Link.create(:source => 75, :target => 41, :value => 1)
Link.create(:source => 75, :target => 70, :value => 1)
Link.create(:source => 75, :target => 71, :value => 1)
Link.create(:source => 76, :target => 64, :value => 1)
Link.create(:source => 76, :target => 65, :value => 1)
Link.create(:source => 76, :target => 66, :value => 1)
Link.create(:source => 76, :target => 63, :value => 1)
Link.create(:source => 76, :target => 62, :value => 1)
Link.create(:source => 76, :target => 48, :value => 1)
Link.create(:source => 76, :target => 58, :value => 1)
